%
% Gabbiani & Cox, Mathematics for Neuroscientists
%
% ip3fundrive,  these functions were generated by ip3sym and translated by
% hand
%
function ip3fundrive

C=0.001:0.001:10; I =1;
[y,t,xo]=ip3fun(C,I);
semilogx(C,xo)
hold on
I=0.75;
[y,t,xo]=ip3fun(C,I);
semilogx(C,xo,'--')
I=0.5;
[y,t,xo]=ip3fun(C,I);
semilogx(C,xo,':')
legend('[IP_3]=1 \muM','[IP_3]=0.75 \muM','[IP_3]=0.5 \muM','location','best')
xlabel('[Ca^{2+}]  (\muM)','fontsize',14)
ylabel('x_{O,\infty}','fontsize',14)

function [yinf,tauy,xOinf] = ip3fun(C,I)
tauy = .590*(943.+.100e4*I).*(500.*C+41.)./(.668e2*I.*C+.590e2*I.*C.^2+.508e1*I+.126e2*C+.662+.557e2*C.^2);
yinf = .312*(.258*C+.212e-1+.198e1*I.*C+.163*I)./(.668*I.*C+.590*I.*C.^2+.508e-1*I+.126*C+.662e-2+.557*C.^2);
k15 = 0.4*I; k58 = 2e-4*C; k48 = k15; k14 = k58; k12 = 0.02*C;
k51 = .052; k85 = 2.1e-4; k84 = .3772; k41=2.9e-5; k21 = 1.64e-3;
xOinf = (k15.*k12.*yinf./(k51+k15)./(k21+k12)).^3;
